controller_list:
  - name: ""
    action_ns: joint_trajectory_action
    type: FollowJointTrajectory
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: gripper_controller
    type: GripperCommand
    action_ns: gripper_action
    default: true
    joints:
      - gripper_finger