controller_list:
  - name: fake_pa10_controller
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - joint_7
  - name: fake_pg70_controller
    joints:
      - gripper_finger